### ISSUE TITLE
Incorrect handling of ampersand in OpenMW data paths

### ISSUE THREAD

**Issue by AnyOldName3** [polemion/Wrye-Mash-Polemos#9]
We've just had a user needing help troubleshooting and one of the issues was a mod with `&` in the name. For quoted paths in `openmw.cfg`, this is the escape character used for paths containing `"`.

Instead of writing 
```
data="K:/Jeux/Morrowind/Data Files/OpenMW Spec. and Normal Maps/04 - OpenMW Spec. & Normal Maps"
```
you should write
```
data="K:/Jeux/Morrowind/Data Files/OpenMW Spec. and Normal Maps/04 - OpenMW Spec. && Normal Maps"
```
or
```
data=K:/Jeux/Morrowind/Data Files/OpenMW Spec. and Normal Maps/04 - OpenMW Spec. & Normal Maps
```
The latter will only work with newer OpenMW versions - older ones required paths with spaces to be quoted.

Some Python code implementing the conversion can be seen here: https://github.com/AnyOldName3/ModOrganizer-to-OpenMW/blob/bf05ad5c9c9690ef89a4c42b199f06baee51cccc/OpenMWExport.py#L134-L143

I'm aware this fork doesn't seem to be maintained, but people are still using it, and this problem doesn't seem to be documented anywhere.

**Comment by polemion** [comment]
Do any OpenMW users actually use it?

To be honest, I didn't notice much interest, so the OpenMW part was shelved pretty early.

I'll see what I can do tomorrow.

**Comment by AnyOldName3** [comment]
Enough people use it that one of them managed to run into this bug. I don't know if it's one unlucky user, or several.

**Comment by polemion** [comment]
Fixed in the following commits, along with many other critical BUGs:
- https://github.com/polemion/Wrye-Mash-Polemos/commit/dbce232bd053ff8e2c49e6ada85c570f07376d7d
- https://github.com/polemion/Wrye-Mash-Polemos/commit/68421a5517e85ae08403e98a9988084682482643

I should have made a branch, but I didn't, so here are the committed OpenMW fixes:
- the ampersand issue,
- Settings dialog BUG, 
- BSAs ordering not working,
- Datamods duplication, 
- esm/omwgame & esp/omwaddon ordering issues, 
- expanded omwgame/omwaddon compatibility,
- ordering issue with the first item in the plugins list,
- max plugin limit is set to infinite (kinda).

Your user may directly use the updated source (will need to rename the `openmw.dat.ren` to `openmw.dat` first though).
Nevertheless, I do intend to prepare a standalone executable soon (hopefully).

**Comment by polemion** [comment]
[Release](https://github.com/polemion/Wrye-Mash-Polemos/releases/tag/openmw_beta)
